[package]
name = "typesafe-sdk-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Client configuration, validation and precedence."

[dependencies]
typesafe-sdk-env.workspace = true
typesafe-sdk-error.workspace = true
typesafe-sdk-headers.workspace = true
typesafe-sdk-log.workspace = true
typesafe-sdk-retry.workspace = true

[dev-dependencies]
typesafe-sdk-retry.workspace = true

[lints]
workspace = true
