[package]
name = "typesafe-sdk-error"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "The TypeSafe error taxonomy."

[dependencies]

[lints]
workspace = true
